version: '3'
services:

  web:
    build:
      context: ./Docker/nginx
      dockerfile: Dockerfile-nginx
    container_name: web-nginx
    ports:
      - 80:80
    links:  # Пробрасывает ссылки для другие контейнеры
      - php-container
      - database
    volumes:
      - ./Docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www:cached

  php-container:
    build:
      context: ./Docker/php
      dockerfile: Dockerfile-php
    working_dir: /var/www
    container_name: web-php
    volumes:
      - ./www:/var/www:cached

  database:
    build:
      context: ./Docker/mysql
      dockerfile: Dockerfile-database
    container_name: web-mysql
    ports:
      - 3306:3306
    volumes:
      #- ./conf/mysql:/etc/mysql/conf.d
      - ./database:/var/lib/mysql #  файлы бд
      - ./www/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: web-pma
    ports:
      - 8686:80
    links:
      - web
    environment:
      PMA_HOST: web-mysql

  mailhog:
    container_name: web-mail
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
